### PR TITLE
FeatherS2 board mappings

### PR DESCRIPTION
**Pull request by RetiredWizard**
I hacked this together and it seems to work for me. I'm not sure I've got everything perfect or even if I missed a post describing a better method, but if not, I figured it might be useful anyway.

FeatherS2 from Unexpected Maker: https://unexpectedmaker.com/shop/feathers2-esp32-s2

### CODE REVIEW

**Comment by arturo182** [comment]
Wow, so sorry, I have absolutely missed this PR. Could you rename the file to `kfw_feathers2_board` just so it's more clear what it's for, and then I can merge.

**Comment by arturo182** [comment]
Thank you so much :)

**Comment by RetiredWizard** [comment]
You're most welcome :)

**Comment by RetiredWizard** [comment]
I don't know if you think it's of any value, but I've expanded both the _board files to include all of the pins defined in the Circuitpython library. If you'd like I can put them up as a pull request as well, so you can take a look at them and decide if you want the extra pins in your files.

**Comment by arturo182** [comment]
I'm not sure myself but sure, make a PR and I can have a look

**Pull request merged**
